//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceDuyTan.ServiceReferenceGPS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceGPS.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckLogin(string login_user_name, string login_password, string serial, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLoginV4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckLoginV4(string login_user_name, string login_password, string serial, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVehicleStatusList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetVehicleStatusList(string ws_user_name, string ws_password, string login_user_name, string login_password, string serial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVehicleEventList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetVehicleEventList(string ws_user_name, string ws_password, string login_user_name, string login_password, string serial, System.DateTime date_frm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVehicleStatusListV3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetVehicleStatusListV3(string login_user_name, string login_password, string serial, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataV4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataV4(string login_user_name, string login_password, string serial, string version, int index);
        
        // CODEGEN: Parameter 'DanhSachSuKienByMaxIdResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachSuKienByMaxId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdResponse DanhSachSuKienByMaxId(WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdRequest request);
        
        // CODEGEN: Parameter 'DanhSachSuKienByMaxIdMultiSiteResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachSuKienByMaxIdMultiSite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdMultiSiteResponse DanhSachSuKienByMaxIdMultiSite(WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdMultiSiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatusLogChuyen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateStatusLogChuyen(string login_user_name, string login_password, string serial, string version, string ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestSession(string login_user_name, string login_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestIPClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestIPClient();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DanhSachSuKienByMaxId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DanhSachSuKienByMaxIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login_user_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string login_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string serial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string trackId;
        
        public DanhSachSuKienByMaxIdRequest() {
        }
        
        public DanhSachSuKienByMaxIdRequest(string login_user_name, string login_password, string serial, string version, int index, string trackId) {
            this.login_user_name = login_user_name;
            this.login_password = login_password;
            this.serial = serial;
            this.version = version;
            this.index = index;
            this.trackId = trackId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DanhSachSuKienByMaxIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DanhSachSuKienByMaxIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataSet")]
        public System.Data.DataSet[] DanhSachSuKienByMaxIdResult;
        
        public DanhSachSuKienByMaxIdResponse() {
        }
        
        public DanhSachSuKienByMaxIdResponse(System.Data.DataSet[] DanhSachSuKienByMaxIdResult) {
            this.DanhSachSuKienByMaxIdResult = DanhSachSuKienByMaxIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DanhSachSuKienByMaxIdMultiSite", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DanhSachSuKienByMaxIdMultiSiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login_user_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string login_password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string serial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string trackId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string webSite;
        
        public DanhSachSuKienByMaxIdMultiSiteRequest() {
        }
        
        public DanhSachSuKienByMaxIdMultiSiteRequest(string login_user_name, string login_password, string serial, string version, int index, string trackId, string webSite) {
            this.login_user_name = login_user_name;
            this.login_password = login_password;
            this.serial = serial;
            this.version = version;
            this.index = index;
            this.trackId = trackId;
            this.webSite = webSite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DanhSachSuKienByMaxIdMultiSiteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DanhSachSuKienByMaxIdMultiSiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataSet")]
        public System.Data.DataSet[] DanhSachSuKienByMaxIdMultiSiteResult;
        
        public DanhSachSuKienByMaxIdMultiSiteResponse() {
        }
        
        public DanhSachSuKienByMaxIdMultiSiteResponse(System.Data.DataSet[] DanhSachSuKienByMaxIdMultiSiteResult) {
            this.DanhSachSuKienByMaxIdMultiSiteResult = DanhSachSuKienByMaxIdMultiSiteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WebServiceDuyTan.ServiceReferenceGPS.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WebServiceDuyTan.ServiceReferenceGPS.ServiceSoap>, WebServiceDuyTan.ServiceReferenceGPS.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckLogin(string login_user_name, string login_password, string serial, string version) {
            return base.Channel.CheckLogin(login_user_name, login_password, serial, version);
        }
        
        public string CheckLoginV4(string login_user_name, string login_password, string serial, string version) {
            return base.Channel.CheckLoginV4(login_user_name, login_password, serial, version);
        }
        
        public System.Data.DataSet GetVehicleStatusList(string ws_user_name, string ws_password, string login_user_name, string login_password, string serial) {
            return base.Channel.GetVehicleStatusList(ws_user_name, ws_password, login_user_name, login_password, serial);
        }
        
        public System.Data.DataSet GetVehicleEventList(string ws_user_name, string ws_password, string login_user_name, string login_password, string serial, System.DateTime date_frm) {
            return base.Channel.GetVehicleEventList(ws_user_name, ws_password, login_user_name, login_password, serial, date_frm);
        }
        
        public System.Data.DataSet GetVehicleStatusListV3(string login_user_name, string login_password, string serial, string version) {
            return base.Channel.GetVehicleStatusListV3(login_user_name, login_password, serial, version);
        }
        
        public System.Data.DataSet GetDataV4(string login_user_name, string login_password, string serial, string version, int index) {
            return base.Channel.GetDataV4(login_user_name, login_password, serial, version, index);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdResponse WebServiceDuyTan.ServiceReferenceGPS.ServiceSoap.DanhSachSuKienByMaxId(WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdRequest request) {
            return base.Channel.DanhSachSuKienByMaxId(request);
        }
        
        public System.Data.DataSet[] DanhSachSuKienByMaxId(string login_user_name, string login_password, string serial, string version, int index, string trackId) {
            WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdRequest inValue = new WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdRequest();
            inValue.login_user_name = login_user_name;
            inValue.login_password = login_password;
            inValue.serial = serial;
            inValue.version = version;
            inValue.index = index;
            inValue.trackId = trackId;
            WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdResponse retVal = ((WebServiceDuyTan.ServiceReferenceGPS.ServiceSoap)(this)).DanhSachSuKienByMaxId(inValue);
            return retVal.DanhSachSuKienByMaxIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdMultiSiteResponse WebServiceDuyTan.ServiceReferenceGPS.ServiceSoap.DanhSachSuKienByMaxIdMultiSite(WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdMultiSiteRequest request) {
            return base.Channel.DanhSachSuKienByMaxIdMultiSite(request);
        }
        
        public System.Data.DataSet[] DanhSachSuKienByMaxIdMultiSite(string login_user_name, string login_password, string serial, string version, int index, string trackId, string webSite) {
            WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdMultiSiteRequest inValue = new WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdMultiSiteRequest();
            inValue.login_user_name = login_user_name;
            inValue.login_password = login_password;
            inValue.serial = serial;
            inValue.version = version;
            inValue.index = index;
            inValue.trackId = trackId;
            inValue.webSite = webSite;
            WebServiceDuyTan.ServiceReferenceGPS.DanhSachSuKienByMaxIdMultiSiteResponse retVal = ((WebServiceDuyTan.ServiceReferenceGPS.ServiceSoap)(this)).DanhSachSuKienByMaxIdMultiSite(inValue);
            return retVal.DanhSachSuKienByMaxIdMultiSiteResult;
        }
        
        public bool UpdateStatusLogChuyen(string login_user_name, string login_password, string serial, string version, string ids) {
            return base.Channel.UpdateStatusLogChuyen(login_user_name, login_password, serial, version, ids);
        }
        
        public string TestSession(string login_user_name, string login_password) {
            return base.Channel.TestSession(login_user_name, login_password);
        }
        
        public string TestIPClient() {
            return base.Channel.TestIPClient();
        }
    }
}
